In [1]:
import os.path
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact
import ipywidgets as widgets
from scipy.stats import hmean
#from datetime import datetime as dtm
import datetime as dtm

In [2]:
df = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dm2_10.csv", encoding="shift_jis")

C:\Users\tssl-34\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df

,記録年,記録月,記録日,記録曜日,記録時刻,文字情報板番号,文字情報板名称,制御区分,情報区分,影響係数,...,休日,時間帯,kcode,降水量,滑り止め,区間長up,速度up,交通量up,渋滞up,事故up
0,2021,10,1,（金）,06:41,7,下豊南本線,自動制御,本線事象,100.0,...,1.0,2.0,NaN,0.0,0.0,6.0,75.0,258.0,NaN,NaN
1,2021,10,1,（金）,06:42,7,下豊南本線,自動制御,本線事象,100.0,...,1.0,2.0,NaN,0.0,0.0,6.0,75.0,258.0,NaN,NaN
2,2021,10,1,（金）,06:43,7,下豊南本線,自動制御,本線事象,100.0,...,1.0,2.0,NaN,0.0,0.0,6.0,75.0,258.0,NaN,NaN
3,2021,10,1,（金）,06:44,7,下豊南本線,自動制御,本線事象,100.0,...,1.0,2.0,NaN,0.0,0.0,6.0,75.0,258.0,NaN,NaN
4,2021,10,1,（金）,06:45,7,下豊南本線,自動制御,本線事象,100.0,...,1.0,2.0,NaN,0.0,0.0,6.0,79.0,231.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4136792,2021,10,31,（日）,23:45,956,森宮本線Ｄ,自動制御,本線事象,1.0,...,3.0,2.0,NaN,0.0,0.0,5.0,105.0,28.0,NaN,NaN
4136793,2021,10,31,（日）,23:56,956,森宮本線Ｄ,自動制御,本線事象,1.0,...,3.0,2.0,NaN,0.0,0.0,5.0,86.0,24.0,NaN,NaN
4136794,2021,10,31,（日）,23:57,956,森宮本線Ｄ,自動制御,本線事象,1.0,...,3.0,2.0,NaN,0.0,0.0,5.0,86.0,24.0,NaN,NaN
4136795,2021,10,31,（日）,23:58,956,森宮本線Ｄ,自動制御,本線事象,1.0,...,3.0,2.0,NaN,0.0,0.0,5.0,86.0,24.0,NaN,NaN
4136796,2021,10,31,（日）,23:59,956,森宮本線Ｄ,自動制御,本線事象,1.0,...,3.0,2.0,NaN,0.0,0.0,5.0,86.0,24.0,NaN,NaN

In [17]:
nip = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dnippo_10_8.csv", encoding="shift_jis")

In [147]:
#df[df.idx=="2021-04-05 10:15:00_1041"].loc[:,"idx":]

In [3]:
df.columns=['記録年', '記録月', '記録日', '記録曜日', '記録時刻', '文字情報板番号', '文字情報板名称', '制御区分',
       '情報区分', '影響係数', '障害係数', '評価値', '提供フラグ', '事象内通番', '原因', '程度', '渋滞長',
       '障害登録番号', '先頭系統名称', '先頭KP', '後尾系統名称', '後尾KP', '入口／出口名称', '特記事項', 'indx',
       'line', 'keito', 'kp', 'name', 'jdp', 'jdpup1', 'jdpup2', 'jdpup3',
       'vsidx', 'risk', 'temp', 'r2p', 'r2n', 'r3p', 'r3n', 'n1p', 'gen', 'tidx', 'tidx5m',
       'idx', 'upidx', '地区名', 'JDP番号', '区間番号', '日付', '時間', '区間長', 'エラー', '速度',
       '交通量', '渋滞', '事故', '休日', '時間帯', 'kcode', '降水量', '滑り止め', '区間長up', '速度up',
       '交通量up', '渋滞up', '事故up']

In [4]:
d=df[df.原因=="リスク"]

In [15]:
d["tvsidx"]=pd.to_datetime(d.tidx).astype(str)+"_"+d.文字情報板番号.astype(str)

C:\Users\tssl-34\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [83]:
d.tvsidx

88           2021-10-1 00:00:00_11
89           2021-10-1 00:01:00_11
90           2021-10-1 00:02:00_11
91           2021-10-1 00:03:00_11
92           2021-10-1 00:04:00_11
                    ...
4136792    2021-10-31 23:45:00_956
4136793    2021-10-31 23:56:00_956
4136794    2021-10-31 23:57:00_956
4136795    2021-10-31 23:58:00_956
4136796    2021-10-31 23:59:00_956
Name: tvsidx, Length: 1428903, dtype: object

In [18]:
dnip=nip.loc[:,["固定パターン番号","固定パターンコメント","系統番号","文字情報板番号",
               "開始時刻","停止時刻","時間差","情報板位置番号","区別番号"]]

In [29]:
dnip["stt"]=pd.to_datetime(dnip.開始時刻)
dnip["endt"]=pd.to_datetime(dnip.停止時刻)

In [46]:
#dnip.iloc[0:1,:]
tt=dnip.iloc[0:1,:]

In [48]:
tt.stt[0]

Timestamp('2021-10-04 12:15:00')

In [51]:
dnip

,固定パターン番号,固定パターンコメント,系統番号,文字情報板番号,開始時刻,停止時刻,時間差,情報板位置番号,区別番号,stt,endt
0,158,事故多発区間 前方注意,1,11,2021/10/4 12:15,2021/10/4 12:17,2,1,1,2021-10-04 12:15:00,2021-10-04 12:17:00
1,156,事故多発区間 車間保て,1,11,2021/10/5 2:45,2021/10/5 3:12,27,1,1,2021-10-05 02:45:00,2021-10-05 03:12:00
2,158,事故多発区間 前方注意,1,11,2021/10/5 8:29,2021/10/5 8:33,4,1,1,2021-10-05 08:29:00,2021-10-05 08:33:00
3,158,事故多発区間 前方注意,1,11,2021/10/5 8:42,2021/10/5 8:43,1,1,1,2021-10-05 08:42:00,2021-10-05 08:43:00
4,158,事故多発区間 前方注意,1,11,2021/10/5 10:29,2021/10/5 10:30,1,1,1,2021-10-05 10:29:00,2021-10-05 10:30:00
...,...,...,...,...,...,...,...,...,...,...,...
44238,160,事故多発区間 速度落せ,80,369,2021/10/29 1:15,2021/10/29 1:20,5,138,2,2021-10-29 01:15:00,2021-10-29 01:20:00
44239,160,事故多発区間 速度落せ,80,369,2021/10/29 3:00,2021/10/29 3:05,5,138,2,2021-10-29 03:00:00,2021-10-29 03:05:00
44240,160,事故多発区間 速度落せ,80,369,2021/10/29 19:24,2021/10/29 19:33,9,138,2,2021-10-29 19:24:00,2021-10-29 19:33:00
44241,160,事故多発区間 速度落せ,80,369,2021/10/30 13:39,2021/10/30 13:47,8,138,2,2021-10-30 13:39:00,2021-10-30 13:47:00
44242,160,事故多発区間 速度落せ,80,369,2021/10/31 13:59,2021/10/31 19:04,305,138,2,2021-10-31 13:59:00,2021-10-31 19:04:00

In [71]:
nipext=[]
for i in range(dnip.shape[0]):
#for i in range(3):
    if i%100==0:
        print(i)
    temp=dnip.iloc[i:i+1,:]
    nxt=temp.iloc[0,9]+dtm.timedelta(minutes=1)
    ent=temp.iloc[0,10]
    nipext.append(temp)
    #print(nxt,ent)
    while nxt<ent:
        temp=dnip.iloc[i:i+1,:]
        temp.loc[:,"stt"]=nxt
        nipext.append(temp)
        nxt=temp.iloc[0,9]+dtm.timedelta(minutes=1)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900
21000
21100
21200
21300
21400
21500
21600
21700
21800
21900
22000
22100
22200
22300
22400
22500
22600
22700
22800
22900
23000
23100
23200
23300
23400
23500
23600
23700
23800
23900
24000
24100
24200
24300
24400
24500
24600
24700
24800
24900
25000
25100
25200
25300
25400
25500
25600
25700
25800
25900
26000
26100
26200
26300
26400
26500
26600
26700
26800
26900
27000
27100
27200
27300
27400
27500
27600
27700
27800
27900
28000
28100
28200
28300
28400
28500
28600
28700
28800
28900
29000
29100
29200
29300
29400
29500
29600
29700
29800
29900
30000
30100
30200
30300
30400
30500
30600
30700
30800
30900
31000
31100
31200
31300
31400
31500
31600
31700
31800
31900
32000
32100
32200
32300
32400
32500
32600
32700
32800
32900
33000
33100
33200
33300
33400
33500
33600
33700
33800
33900
34000
34100
34200
34300
34400
34500
34600
34700
34800
34900
35000
35100
35200
35300
35400
35500
35600
35700
35800
35900
36000
36100
36200
36300
36400
36500
36600
36700
36800
36900
37000
37100
37200
37300
37400
37500
37600
37700
37800
37900
38000
38100
38200
38300
38400
38500
38600
38700
38800
38900
39000
39100
39200
39300
39400
39500
39600
39700
39800
39900
40000
40100
40200
40300
40400
40500
40600
40700
40800
40900
41000
41100
41200
41300
41400
41500
41600
41700
41800
41900
42000
42100
42200
42300
42400
42500
42600
42700
42800
42900
43000
43100
43200
43300
43400
43500
43600
43700
43800
43900
44000
44100
44200

In [72]:
dnipe=pd.concat(nipext, axis = 0, ignore_index = True)

In [73]:
dnipe

,固定パターン番号,固定パターンコメント,系統番号,文字情報板番号,開始時刻,停止時刻,時間差,情報板位置番号,区別番号,stt,endt
0,158,事故多発区間 前方注意,1,11,2021/10/4 12:15,2021/10/4 12:17,2,1,1,2021-10-04 12:15:00,2021-10-04 12:17:00
1,158,事故多発区間 前方注意,1,11,2021/10/4 12:15,2021/10/4 12:17,2,1,1,2021-10-04 12:16:00,2021-10-04 12:17:00
2,156,事故多発区間 車間保て,1,11,2021/10/5 2:45,2021/10/5 3:12,27,1,1,2021-10-05 02:45:00,2021-10-05 03:12:00
3,156,事故多発区間 車間保て,1,11,2021/10/5 2:45,2021/10/5 3:12,27,1,1,2021-10-05 02:46:00,2021-10-05 03:12:00
4,156,事故多発区間 車間保て,1,11,2021/10/5 2:45,2021/10/5 3:12,27,1,1,2021-10-05 02:47:00,2021-10-05 03:12:00
...,...,...,...,...,...,...,...,...,...,...,...
891677,160,事故多発区間 速度落せ,80,369,2021/10/31 13:59,2021/10/31 19:04,305,138,2,2021-10-31 18:59:00,2021-10-31 19:04:00
891678,160,事故多発区間 速度落せ,80,369,2021/10/31 13:59,2021/10/31 19:04,305,138,2,2021-10-31 19:00:00,2021-10-31 19:04:00
891679,160,事故多発区間 速度落せ,80,369,2021/10/31 13:59,2021/10/31 19:04,305,138,2,2021-10-31 19:01:00,2021-10-31 19:04:00
891680,160,事故多発区間 速度落せ,80,369,2021/10/31 13:59,2021/10/31 19:04,305,138,2,2021-10-31 19:02:00,2021-10-31 19:04:00
891681,160,事故多発区間 速度落せ,80,369,2021/10/31 13:59,2021/10/31 19:04,305,138,2,2021-10-31 19:03:00,2021-10-31 19:04:00

In [85]:
dnipe["tvsidx"]=dnipe.stt.astype(str)+"_"+dnipe.文字情報板番号.astype(str)

In [86]:
dnipe.tvsidx

0          2021-10-04 12:15:00_11
1          2021-10-04 12:16:00_11
2          2021-10-05 02:45:00_11
3          2021-10-05 02:46:00_11
4          2021-10-05 02:47:00_11
                   ...
891677    2021-10-31 18:59:00_369
891678    2021-10-31 19:00:00_369
891679    2021-10-31 19:01:00_369
891680    2021-10-31 19:02:00_369
891681    2021-10-31 19:03:00_369
Name: tvsidx, Length: 891682, dtype: object

In [87]:
dnipe.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dnipext10.csv", index = False, encoding="shift_jis")

In [14]:
dnipe = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dnipext10.csv", encoding="shift_jis")

In [18]:
dm=pd.merge(d,dnipe, on="tvsidx", how="inner")#, sort=True

In [19]:
dmf=dm[~pd.isna(dm.stt)]

In [20]:
dmf

,記録年,記録月,記録日,記録曜日,記録時刻,文字情報板番号_x,文字情報板名称,制御区分,情報区分,影響係数,...,固定パターンコメント,系統番号,文字情報板番号_y,開始時刻,停止時刻,時間差,情報板位置番号,区別番号,stt,endt
0,2021,10,4,（月）,06:46,7,下豊南本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,2,7,2021/10/4 6:45,2021/10/4 6:55,10,5,1,2021-10-04 06:46:00,2021-10-04 06:55:00
1,2021,10,4,（月）,06:47,7,下豊南本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,2,7,2021/10/4 6:45,2021/10/4 6:55,10,5,1,2021-10-04 06:47:00,2021-10-04 06:55:00
2,2021,10,4,（月）,06:48,7,下豊南本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,2,7,2021/10/4 6:45,2021/10/4 6:55,10,5,1,2021-10-04 06:48:00,2021-10-04 06:55:00
3,2021,10,4,（月）,06:49,7,下豊南本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,2,7,2021/10/4 6:45,2021/10/4 6:55,10,5,1,2021-10-04 06:49:00,2021-10-04 06:55:00
4,2021,10,4,（月）,06:50,7,下豊南本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,2,7,2021/10/4 6:45,2021/10/4 6:55,10,5,1,2021-10-04 06:50:00,2021-10-04 06:55:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525876,2021,10,31,（日）,18:24,694,下白川本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,62,694,2021/10/31 18:20,2021/10/31 18:25,5,129,1,2021-10-31 18:24:00,2021-10-31 18:25:00
525877,2021,10,31,（日）,18:31,694,下白川本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,62,694,2021/10/31 18:30,2021/10/31 18:35,5,129,1,2021-10-31 18:31:00,2021-10-31 18:35:00
525878,2021,10,31,（日）,18:32,694,下白川本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,62,694,2021/10/31 18:30,2021/10/31 18:35,5,129,1,2021-10-31 18:32:00,2021-10-31 18:35:00
525879,2021,10,31,（日）,18:33,694,下白川本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,62,694,2021/10/31 18:30,2021/10/31 18:35,5,129,1,2021-10-31 18:33:00,2021-10-31 18:35:00
525880,2021,10,31,（日）,18:34,694,下白川本線,自動制御,本線事象,1.0,...,事故多発区間 前方注意,62,694,2021/10/31 18:30,2021/10/31 18:35,5,129,1,2021-10-31 18:34:00,2021-10-31 18:35:00

In [21]:
dmf.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dnipfin10.csv", index = False, encoding="shift_jis")

In [6]:
#d=df.loc[:,["idx","tidx","tidx5m","indx","jdp","keito","r2p","r2n","r3p","r3n","n1p","gen","区間長","渋滞","事故","休日","時間帯","降水量"]]
#dtest=df.loc[:,["事象内通番","原因","程度"]]

In [7]:
#dtest[~dtest.duplicated(subset="事象内通番")]

In [23]:
dc=d[(d.渋滞==1)|(d.渋滞==2)]

In [25]:
dc

,idx,tidx,tidx5m,indx,jdp,keito,r2p,r2n,r3p,r3n,n1p,gen,区間長,渋滞,事故,休日,時間帯,降水量
15079,2021-04-05 12:50:00_536,2021-4-5 12:50:00,2021-04-05 12:50:00,194,536.0,17.0,0,0,1,0,0,[],5.0,1.0,NaN,1.0,1.0,0.0
15080,2021-04-05 12:50:00_536,2021-4-5 12:51:00,2021-04-05 12:50:00,194,536.0,17.0,0,0,1,0,0,[],5.0,1.0,NaN,1.0,1.0,0.0
15081,2021-04-05 12:50:00_536,2021-4-5 12:52:00,2021-04-05 12:50:00,194,536.0,17.0,0,0,1,0,0,[],5.0,1.0,NaN,1.0,1.0,0.0
15082,2021-04-05 12:50:00_536,2021-4-5 12:53:00,2021-04-05 12:50:00,194,536.0,17.0,0,0,1,0,0,[],5.0,1.0,NaN,1.0,1.0,0.0
15083,2021-04-05 12:50:00_536,2021-4-5 12:54:00,2021-04-05 12:50:00,194,536.0,17.0,0,0,1,0,0,[],5.0,1.0,NaN,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2237576,2021-04-30 18:15:00_879,2021-4-30 18:15:00,2021-04-30 18:15:00,416,879.0,39.0,1,0,0,0,0,[],3.0,1.0,NaN,1.0,1.0,0.0
2240497,2021-04-30 19:25:00_433,2021-4-30 19:26:00,2021-04-30 19:25:00,545,433.0,21.0,0,1,0,0,1,['渋滞'],5.0,2.0,NaN,1.0,1.0,0.0
2240498,2021-04-30 19:25:00_433,2021-4-30 19:27:00,2021-04-30 19:25:00,545,433.0,21.0,0,1,0,0,1,['渋滞'],5.0,2.0,NaN,1.0,1.0,0.0
2240499,2021-04-30 19:25:00_433,2021-4-30 19:28:00,2021-04-30 19:25:00,545,433.0,21.0,0,1,0,0,1,['渋滞'],5.0,2.0,NaN,1.0,1.0,0.0
2240500,2021-04-30 19:25:00_433,2021-4-30 19:29:00,2021-04-30 19:25:00,545,433.0,21.0,0,1,0,0,1,['渋滞'],5.0,2.0,NaN,1.0,1.0,0.0

In [89]:
dp2=dc.groupby(["indx","r2p"], as_index=False).count().loc[:,["indx","r2p","idx"]]
dp3=dc.groupby(["indx","r3p"], as_index=False).count().loc[:,["indx","r3p","idx"]]
dn2=dc.groupby(["indx","r2n"], as_index=False).count().loc[:,["indx","r2n","idx"]]
dn3=dc.groupby(["indx","r3n"], as_index=False).count().loc[:,["indx","r3n","idx"]]

In [90]:
d2p=dp2[dp2.r2p==1]
d3p=dp3[dp3.r3p==1]
d2n=dn2[dn2.r2n==1]
d3n=dn3[dn3.r3n==1]

In [91]:
dm=pd.merge(d2p,d2n, on="indx", how="outer", sort=True)
dm=pd.merge(dm,d3p, on="indx", how="outer", sort=True)
dm=pd.merge(dm,d3n, on="indx", how="outer", sort=True)

In [92]:
dm

     indx  r2p   idx_x  r2n  idx_y  r3p  idx_x  r3n  idx_y
0       7  1.0   459.0  1.0  101.0  1.0   22.0  1.0  102.0
1       8  1.0  1114.0  1.0  413.0  1.0  158.0  1.0  862.0
2      11  1.0    12.0  1.0   21.0  1.0   17.0  1.0  285.0
3      17  NaN     NaN  1.0  159.0  1.0    4.0  1.0  240.0
4      20  NaN     NaN  1.0    5.0  NaN    NaN  NaN    NaN
..    ...  ...     ...  ...    ...  ...    ...  ...    ...
165   822  1.0    12.0  1.0   21.0  1.0   17.0  1.0  277.0
166   823  1.0    21.0  1.0   12.0  1.0  175.0  1.0  119.0
167   824  1.0   458.0  1.0  100.0  1.0   22.0  1.0  101.0
168   825  1.0  1104.0  1.0  402.0  1.0  157.0  1.0  829.0
169   826  1.0     5.0  1.0  112.0  1.0    4.0  1.0   47.0

[170 rows x 9 columns]

In [93]:
del dm["r2p"],dm["r2n"],dm["r3p"],dm["r3n"]

In [94]:
dm.columns=["indx","r2p","r2n","r3p","r3n"]

In [95]:
dm

     indx     r2p    r2n    r3p    r3n
0       7   459.0  101.0   22.0  102.0
1       8  1114.0  413.0  158.0  862.0
2      11    12.0   21.0   17.0  285.0
3      17     NaN  159.0    4.0  240.0
4      20     NaN    5.0    NaN    NaN
..    ...     ...    ...    ...    ...
165   822    12.0   21.0   17.0  277.0
166   823    21.0   12.0  175.0  119.0
167   824   458.0  100.0   22.0  101.0
168   825  1104.0  402.0  157.0  829.0
169   826     5.0  112.0    4.0   47.0

[170 rows x 5 columns]

In [7]:
#d[d.idx=="2021-04-05 10:15:00_1041"]

In [8]:
d["走行台キロ"]=d.区間長*d.交通量/10

In [9]:
d["idx5m"]=d.tidx5m+"_"+d.indx.astype(str)

In [10]:
cnt5m = pd.DataFrame(d.groupby("idx5m").count().loc[:,"記録日"])

In [11]:
cnt5m["cnt5m"]=cnt5m.記録日

In [12]:
del cnt5m["記録日"]

In [13]:
cnt5m = cnt5m.reset_index()

In [14]:
dm = pd.merge(d,cnt5m, on="idx5m", how="left")

In [15]:
dm["事故5m"]=dm.事故/dm.cnt5m
dm["速度5m"]=dm.速度/dm.cnt5m
dm["交通量5m"]=dm.交通量/dm.cnt5m
dm["事故u5m"]=dm.事故up/dm.cnt5m
dm["速度u5m"]=dm.速度up/dm.cnt5m
dm["交通量u5m"]=dm.交通量up/dm.cnt5m

In [16]:
d2=dm[~pd.isna(dm.時間帯)]

In [17]:
d2.shape[0]

4134730

In [18]:
d2[d2.渋滞==0]

,記録日,記録時刻,idx,tidx,tidx5m,indx,jdp,jdpup1,keito,r2p,...,事故up,走行台キロ,idx5m,cnt5m,事故5m,速度5m,交通量5m,事故u5m,速度u5m,交通量u5m
22649,1,07:10,2021-10-01 07:10:00_70,2021-10-1 07:10:00,2021-10-01 07:10:00,7,70.0,71.0,2.0,0,...,NaN,109.0,2021-10-01 07:10:00_7,5,NaN,12.8,43.6,NaN,15.6,43.6
22650,1,07:11,2021-10-01 07:10:00_70,2021-10-1 07:11:00,2021-10-01 07:10:00,7,70.0,71.0,2.0,0,...,NaN,109.0,2021-10-01 07:10:00_7,5,NaN,12.8,43.6,NaN,15.6,43.6
22651,1,07:12,2021-10-01 07:10:00_70,2021-10-1 07:12:00,2021-10-01 07:10:00,7,70.0,71.0,2.0,0,...,NaN,109.0,2021-10-01 07:10:00_7,5,NaN,12.8,43.6,NaN,15.6,43.6
22652,1,07:13,2021-10-01 07:10:00_70,2021-10-1 07:13:00,2021-10-01 07:10:00,7,70.0,71.0,2.0,0,...,NaN,109.0,2021-10-01 07:10:00_7,5,NaN,12.8,43.6,NaN,15.6,43.6
22653,1,07:14,2021-10-01 07:10:00_70,2021-10-1 07:14:00,2021-10-01 07:10:00,7,70.0,71.0,2.0,0,...,NaN,109.0,2021-10-01 07:10:00_7,5,NaN,12.8,43.6,NaN,15.6,43.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4132612,31,17:25,2021-10-31 17:25:00_23,2021-10-31 17:25:00,2021-10-31 17:25:00,821,23.0,24.0,1.0,0,...,NaN,108.0,2021-10-31 17:25:00_821,5,NaN,5.4,43.2,NaN,4.4,43.2
4132613,31,17:26,2021-10-31 17:25:00_23,2021-10-31 17:26:00,2021-10-31 17:25:00,821,23.0,24.0,1.0,0,...,NaN,108.0,2021-10-31 17:25:00_821,5,NaN,5.4,43.2,NaN,4.4,43.2
4132614,31,17:27,2021-10-31 17:25:00_23,2021-10-31 17:27:00,2021-10-31 17:25:00,821,23.0,24.0,1.0,0,...,NaN,108.0,2021-10-31 17:25:00_821,5,NaN,5.4,43.2,NaN,4.4,43.2
4132615,31,17:28,2021-10-31 17:25:00_23,2021-10-31 17:28:00,2021-10-31 17:25:00,821,23.0,24.0,1.0,0,...,NaN,108.0,2021-10-31 17:25:00_821,5,NaN,5.4,43.2,NaN,4.4,43.2
4132616,31,17:29,2021-10-31 17:25:00_23,2021-10-31 17:29:00,2021-10-31 17:25:00,821,23.0,24.0,1.0,0,...,NaN,108.0,2021-10-31 17:25:00_821,5,NaN,5.4,43.2,NaN,4.4,43.2

In [19]:
dmf=d2[(d2.渋滞!=1)&(d2.渋滞!=2)]

In [20]:
dmc=d2[(d2.渋滞==1)|(d2.渋滞==2)]

In [21]:
print(d2.shape[0])
print(dmc.shape[0])
print(dmf.shape[0])
dmc.shape[0]+dmf.shape[0]

4134730
320602
3814128

4134730

In [22]:
dt1=dmf[dmf.時間帯==1]
dt2=dmf[dmf.時間帯==2]

In [23]:
print(dt1.shape[0])
print(dt2.shape[0])
dt1.shape[0]+dt2.shape[0]+dmc.shape[0]

2749492
1064636

4134730

In [24]:
dt1_1=dt1.iloc[:1000000,:]
dt1_2=dt1.iloc[1000000:2000000,:]
dt1_3=dt1.iloc[2000000:3000000,:]
#dt1h1_4=dt1h1.iloc[3000000:,:]

dt2_1=dt2.iloc[:1000000,:]
dt2_2=dt2.iloc[1000000:2000000,:]
#dt1h2_3=dt1h2.iloc[2000000:,:]

In [25]:
dmc.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/resultmoji2/dmc10.csv", index = False, encoding="shift_jis")

dt1_1.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/resultmoji2/dt1_1_10.csv", index = False, encoding="shift_jis")
dt1_2.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/resultmoji2/dt1_2_10.csv", index = False, encoding="shift_jis")
dt1_3.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/resultmoji2/dt1_3_10.csv", index = False, encoding="shift_jis")
#dt1h1_4.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/resultrisk/dt1h1_4_09.csv", index = False, encoding="shift_jis")

dt2_1.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/resultmoji2/dt2_1_10.csv", index = False, encoding="shift_jis")
dt2_2.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/resultmoji2/dt2_2_10.csv", index = False, encoding="shift_jis")
#dt1h2_3.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/resultrisk/dt1h2_3_06.csv", index = False, encoding="shift_jis")

In [ ]:
#dm.columns=['記録年', '記録月', '記録日', '記録曜日', '記録時刻', '文字情報板番号', '文字情報板名称', '制御区分',
       '情報区分', '影響係数', '障害係数', '評価値', '提供フラグ', '事象内通番', '原因', '程度', '渋滞長',
       '障害登録番号', '先頭系統名称', '先頭KP', '後尾系統名称', '後尾KP', '入口／出口名称', '特記事項', 'indx',
       'line', 'keito', 'kp', 'name', 'jdp', 'jdpup1', 'jdpup2', 'jdpup3',
       'vsidx', 'risk', 'temp', 'r2p', 'r2n', 'r3p', 'r3n', 'n1p', 'gen', 'tidx', 'tidx5m',
       'idx', 'upidx', '地区名', 'JDP番号', '区間番号', '日付', '時間', '区間長', 'エラー', '速度',
       '交通量', '渋滞', '事故', '休日', '時間帯', 'kcode', '降水量', '滑り止め', '区間長up', '速度up',
       '交通量up', '渋滞up', '事故up']

In [ ]:
#d=dm.loc[:,["記録日","記録時刻","tidx","tidx5m","indx","keito","r2p","r2n","r3p","r3n","n1p","gen","区間長","速度","交通量","渋滞","事故","休日","時間帯","降水量","区間長up","速度up","交通量up","渋滞up","事故up"]]

In [ ]:
d["idx5m"]=d.tidx5m+"_"+d.indx.astype(str)

In [ ]:
cnt5m = pd.DataFrame(d.groupby("idx5m").count().loc[:,"記録日"])

In [ ]:
cnt5m["cnt5m"]=cnt5m.記録日

In [ ]:
del cnt5m["記録日"]

In [ ]:
cnt5m = cnt5m.reset_index()

In [ ]:
dm = pd.merge(d,cnt5m, on="idx5m", how="left")

In [ ]:
dm["事故5m"]=dm.事故/dm.cnt5m
dm["速度5m"]=dm.速度/dm.cnt5m
dm["交通量5m"]=dm.交通量/dm.cnt5m
dm["事故u5m"]=dm.事故up/dm.cnt5m
dm["速度u5m"]=dm.速度up/dm.cnt5m
dm["交通量u5m"]=dm.交通量up/dm.cnt5m

In [ ]:
dm.記録時刻.str[:2]

In [ ]:
dm["keito_hour"]=dm.keito.astype(str)+"_"+dm.記録時刻.str[:2]

In [ ]:
#keitoh = dm.groupby("keito_hour").agg({"r2p":np.sum,"r2n":np.sum,"r3p":np.sum,"r3n":np.sum,
#         "事故5m":np.sum,"速度5m":np.mean,"交通量5m":np.mean,})
keitoh = dm.groupby("keito_hour").agg({"r2p":np.sum,"r2n":np.sum,"r3p":np.sum,"r3n":np.sum,
         "事故5m":np.sum})

In [ ]:
cntkh = dm.groupby("keito_hour").count().loc[:,"記録日"]

In [ ]:
keitoh["cntkh"]=cntkh

In [ ]:
keitoh["idx"]=keitoh.index

In [ ]:
keitoh.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/keihour04.csv", index = False, encoding="shift_jis")

In [ ]:
keito = dm.groupby("keito").agg({"r2p":np.sum,"r2n":np.sum,"r3p":np.sum,"r3n":np.sum,
        "事故5m":np.sum,"速度5m":np.mean,"交通量5m":np.mean,})
#keito = dm.groupby("keito").agg({"r2p":np.sum,"r2n":np.sum,"r3p":np.sum,"r3n":np.sum})

In [ ]:
cntk = dm.groupby("keito").count().loc[:,"記録日"]

In [ ]:
keito["cntk"]=cntk

In [ ]:
keito["rsum"]=keito.r2p+keito.r2n+keito.r3p+keito.r3n

In [ ]:
keito

In [ ]:
dc.shape[0]

In [ ]:
dc["indx"]=dc.文字情報板番号

In [ ]:
vs = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/CHSVSB_情報板3.csv", encoding="shift_jis")

In [ ]:
vs

In [ ]:
dc2 = pd.merge(dc,vs, on="indx", how="left")

In [ ]:
dc3 = dc2[~pd.isna(dc2.line)]

In [ ]:
dc3

In [ ]:
#dc3["drp"]=dc3.記録日.astype(str)+"_"+dc3.記録時刻+"_"+dc3.文字情報板番号.astype(str)+"_"+dc3.事象内通番.astype(str)+"_"+dc3.原因+"_"+dc3.程度

In [ ]:
dc3["vsidx"]=dc3.記録日.astype(str)+"_"+dc3.記録時刻+"_"+dc3.文字情報板番号.astype(str)

In [ ]:
#dc3d = dc3[~dc3.duplicated(subset="drop")]
dc3d = dc3[~dc3.duplicated()]

In [ ]:
t = dc3d[dc3d.vsidx=="14_00:23_158"].iloc[:,5:]

In [ ]:
dc3d[dc3d.vsidx=="14_00:23_158"].iloc[:,5:]

In [ ]:
print(dc3.shape[0])
print(dc3d.shape[0])

In [ ]:
dc3d.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dc3d04.csv", index = False, encoding="shift_jis")

In [ ]:
dc3r = dc3d[dc3d.原因=="リスク"]

In [ ]:
dc3r["risk"]=1

In [ ]:
dc3idx = dc3r.loc[:,["vsidx","risk"]]

In [ ]:
dc3idx

In [ ]:
dc4 = pd.merge(dc3d,dc3idx, on="vsidx", how="left")

In [ ]:
dc4.shape[0]

In [ ]:
dc3.shape[0]

In [ ]:
dc4[(dc4.risk==1)&(dc4.原因=="リスク")&(dc4.提供フラグ!=1)].shape[0]
#dc4[(dc4.risk==1)&(dc4.原因!="リスク")&(dc4.提供フラグ==1)].shape[0]

In [ ]:
#dc4[(dc4.risk==1)&(dc4.原因=="リスク")&(dc4.提供フラグ!=1)].shape[0]
dc4[(dc4.risk==1)&(dc4.原因!="リスク")&(dc4.提供フラグ==1)].shape[0]

In [ ]:
dc4r = dc4[dc4.risk==1]

In [ ]:
dc4r.shape[0]

In [ ]:
dc4r.iloc[:5].loc[:,["記録日","記録時刻","原因","vsidx","risk"]]

In [ ]:
dc4r.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dc4r04.csv", index = False, encoding="shift_jis")

In [ ]:
dc4r[~dc4r.duplicated(subset="vsidx")].shape[0]

In [ ]:
def ts(d):
    return d.原因.values
def ts2(d):
    return d.程度.values
def ts3(d):
    return d.提供フラグ.values

In [ ]:
temp=dc4r.groupby("vsidx").apply(ts)
temp2=dc4r.groupby("vsidx").apply(ts2)
temp3=dc4r.groupby("vsidx").apply(ts3)

In [ ]:
dc5 = pd.DataFrame(temp)

In [ ]:
dc5["vsidx"]=dc5.index

In [ ]:
dc5["gen"]=dc5[0]

In [ ]:
dc5["tei"]=temp2

In [ ]:
dc5["flg"]=temp3

In [ ]:
del dc5[0]

In [ ]:
dc5.shape[0]

In [ ]:
vsidx=dc5.vsidx.values
gen=dc5.gen.values
tei=dc5.tei.values
flg=dc5.flg.values

In [ ]:
cnt=[]
cntstr=[]
for i in range(gen.shape[0]):
#for i in range(3):
    ri2p=0
    ri2n=0
    ri3p=0
    ri3n=0
    nori=0
    nostr=[]
    for j in range(gen[i].shape[0]):
        if gen[i][j]=="リスク":
            if tei[i][j]=="リスク２":
                if flg[i][j]==1:
                    ri2p=ri2p+1
                else:
                    ri2n=ri2n+1
            else:
                if flg[i][j]==1:
                    ri3p=ri3p+1
                else:
                    ri3n=ri3n+1
        else:
            if flg[i][j]==1:
                nori=nori+1
                nostr.append(gen[i][j])
    cnt.append([vsidx[i],ri2p,ri2n,ri3p,ri3n,nori])
    cntstr.append(nostr)

In [ ]:
cntd = pd.DataFrame(cnt)

In [ ]:
cntd["gen"]=cntstr

In [ ]:
tt = dc4r[dc4r.vsidx=="14_00:23_158"].iloc[:,5:]

In [ ]:
tt.shape[0]

In [ ]:
tt[~tt.duplicated()].shape[0]

In [ ]:
cntd[cntd[5]>1]

In [ ]:
cntd["vsidx"]=cntd[0]

In [ ]:
cntd.shape[0]

In [ ]:
df = pd.merge(dc4r,cntd, on="vsidx", how="left")

In [ ]:
df.shape[0]

In [ ]:
df2=df[~df.duplicated(subset="vsidx")]

In [ ]:
df2.shape[0]

In [ ]:
df2

In [ ]:
df2.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/df2_04.csv", index = False, encoding="shift_jis")

In [ ]:
df2 = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/df2_04.csv", encoding="shift_jis")

In [ ]:
df2["tidx"]=df2.記録年.astype(str)+"-"+df2.記録月.astype(str)+"-"+df2.記録日.astype(str)+" "+df2.記録時刻+":00"

In [ ]:
df2["tidx5m"]=pd.to_datetime(df2.tidx).dt.round("5T")

In [ ]:
df2[pd.isna(df2.jdp)]

In [ ]:
df2["idx"]=df2.tidx5m.astype(str)+"_"+df2.jdp.astype(int).astype(str)

In [ ]:
df2["upidx"]=df2.tidx5m.astype(str)+"_"+df2.jdpup1.astype(int).astype(str)

In [ ]:
dff = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/result/dff4.csv", encoding="shift_jis")

In [ ]:
dff2=dff[pd.isna(dff.エラー)]

In [ ]:
dff3=dff2[dff2.速度<200]

In [ ]:
dffup=dff3.loc[:,["idx","区間長","速度","交通量","渋滞","事故"]]

In [ ]:
dffup.columns=["upidx","区間長up","速度up","交通量up","渋滞up","事故up"]

In [ ]:
dffup

In [ ]:
dm = pd.merge(df2,dff3, on="idx", how="left")

In [ ]:
dm.iloc[:5,35:]

In [ ]:
dm2 = pd.merge(dm,dffup, on="upidx", how="left")

In [ ]:
dm2

In [ ]:
dm2.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dm2_04.csv", index = False, encoding="shift_jis")

In [ ]:
df[df.vsidx=="4_00:03_11"].loc[:,"原因"]

In [ ]:
df2 = df[~df.duplicated(subset="vsidx")]

In [ ]:
df2.iloc[1,:]

In [ ]:
dc4r

In [ ]:
temp2 = dc4r[["vsidx","indx"]].groupby("vsidx").count()

In [ ]:
temp2[temp2.indx>5]

In [ ]:
temp = dc4r[(dc4r.vsidx=="10_12:52_368")|(dc4r.vsidx=="9_23:37_545")]

In [ ]:
def ts(d):
    return d.原因.values
def ts2(d):
    return d.提供フラグ.values

In [ ]:
temp2 = temp.groupby("vsidx").apply(ts)
temp3 = temp.groupby("vsidx").apply(ts2)

In [ ]:
print(temp2)
print(temp3)

In [ ]:
tempr = dc4[(dc4.risk==1)&(dc4.原因=="リスク")]

In [ ]:
tempnr = dc4[(dc4.risk==1)&(dc4.原因!="リスク")]

In [ ]:
temp.shape[0]==tempr.shape[0]+tempnr.shape[0]

In [ ]:
print(tempr.shape[0])
print(tempnr.shape[0])
print(tempr[tempr.提供フラグ==1].shape[0])
print(tempr[tempr.提供フラグ!=1].shape[0])
print(tempnr[tempnr.提供フラグ==1].shape[0])
print(tempnr[tempnr.提供フラグ!=1].shape[0])

In [ ]:
dc3a = dc3.loc[:,["記録日","記録時刻","文字情報板番号","提供フラグ","原因","程度","特記事項"]]

In [ ]:
dc3b = dc3a[((dc3a.原因=="リスク")&(dc3a.提供フラグ!=1))|(dc3a.提供フラグ==1)]

In [ ]:
dc3b

In [ ]:
dc3b[dc3b.提供フラグ!=1]

In [ ]:
dc3amoji2 = dc3a[dc3a.文字情報板番号==17]

In [ ]:
dc2=dc[dc.原因=="リスク"]

In [ ]:
dc2

In [ ]:
dc2.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/moji4.csv", index = False, encoding="shift_jis")

In [ ]:
dc3=dc2[dc2.提供フラグ==1]

In [ ]:
dc3

In [ ]:
dc3.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/moji4hyoji.csv", index = False, encoding="shift_jis")

In [ ]:
dc["dtt"]=dc["dt"]+" "+dc["tim"]

In [ ]:
dc["dtt2"] = pd.to_datetime(dc.dtt)

In [ ]:
dtt = pd.DataFrame(dc[dc["num"]==1].dtt2)

In [ ]:
#dtt.dtt=dtt.dtt.astype(str)

In [ ]:
dtt

In [ ]:
occerr = dc[dc.occ>200].drop_duplicates(subset="num")

In [ ]:
occerr

In [ ]:
occerr.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/occerr4.csv", index = False)

In [ ]:
kens = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/kenchiki_s2.csv", header=None, encoding="shift_jis")

In [ ]:
kens.columns=["num"]

In [ ]:
kens

In [ ]:
sec = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/section_add.csv", encoding="shift_jis")
#jdp = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/JDP2.csv", encoding="shift_jis")

In [ ]:
#jdpd = jdp.loc[:,["JDP番号","JDP担当範囲","渋滞検知器番号1","渋滞検知器番号2","渋滞検知器番号3","渋滞検知器番号4","区間番号"]]

In [ ]:
noken = sec[pd.isna(sec.検知器番号1)].区間番号

In [ ]:
noken.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/noken.csv", index = False)

In [ ]:
dc

In [ ]:
sec

In [ ]:
sec_n = sec.区間番号
sec_1 = sec.検知器番号1
sec_2 = sec.検知器番号2
sec_3 = sec.検知器番号3
sec_4 = sec.検知器番号4

df = []
dtt["sec"] = 0

for idx in range(sec.shape[0]):
#for idx in range(5):
    secn = sec_n.values[idx]
    dtt["sec"] = secn
    
    tempc=[]
    temp1 = dc[dc["num"]==sec_1.values[idx]]
    tempc = pd.merge(dtt,temp1, on="dtt2")
    
    print(temp1)
    print(tempc)
    
    if pd.notna(sec_2.values[idx]):
        temp2 = dc[dc["num"]==sec_2.values[idx]]
        tempc = pd.merge(tempc,temp2, on="dtt2")
    
    if pd.notna(sec_3.values[idx]):
        temp3 = dc[dc["num"]==sec_3.values[idx]]
        tempc = pd.merge(tempc,temp3, on="dtt2")
    
    if pd.notna(sec_4.values[idx]):
        temp4 = dc[dc["num"]==sec_4.values[idx]]
        tempc = pd.merge(tempc,temp4, on="dtt2")
    
    tempv = tempc.values
    tempd = pd.DataFrame(tempv)
    print(tempd)
    df.append(tempd)

In [ ]:
#dc[dc["num"]==sec_1.values[0]]
#dc[dc["num"]==2508]

In [ ]:
dfc = pd.concat(df, axis = 0, ignore_index=True)

In [ ]:
dfc[dfc[1]==333]

In [ ]:
dfc.iloc[0,:]

In [ ]:
trf = dfc[6].values.tolist()
trf1 = dfc[6].values.tolist()
trf2 = dfc[16].values.tolist()
trf3 = dfc[26].values.tolist()
trf4 = dfc[36].values.tolist()

In [ ]:
len(trf1)

In [ ]:
for i in range(len(trf1)):
#for i in range(11):
    if not pd.isna(trf2[i]):
        #print(trf2[i])
        if not pd.isna(trf3[i]):
            #rint(trf3[i])
            if not pd.isna(trf4[i]):
                trf[i]=trf1[i]+trf2[i]+trf3[i]+trf4[i]
            else:
                trf[i]=trf1[i]+trf2[i]+trf3[i]
        else:
            trf[i]=trf1[i]+trf2[i]
    else:
        trf[i]=trf1[i]

In [ ]:
dfc.insert(1,"trf",trf)

In [ ]:
dfc[dfc[1]==333]

In [ ]:
dfc

In [ ]:
temp=dfc[dfc[8]>65500][1]

In [ ]:
temp

In [ ]:
temp[temp!=518]

In [ ]:
dfcidx = dfc.iloc[:,:3]

In [ ]:
dfcidx[dfcidx[1]==333]

In [ ]:
dfcidx.insert(0,"idx",dfcidx[0].astype(str)+"_"+dfcidx[1].astype(str))

In [ ]:
dfcidx

In [ ]:
#ttt3 = dfcidx[dfcidx[0]=="2021-04-30 11:10:00"]

In [ ]:
#ttt3[ttt3[1]==27]

In [ ]:
dfcidx[dfcidx[1]==333]

In [ ]:
dfcidx[pd.isna(dfcidx.trf)]

In [ ]:
jdp = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/JDP3.csv", encoding="shift_jis")

In [ ]:
jdp

In [ ]:
jdpd = jdp.loc[:,["JDP番号","地区名","JDP担当範囲","渋滞検知器番号1","渋滞検知器番号2","渋滞検知器番号3","渋滞検知器番号4","区間番号修正"]]

In [ ]:
dtt2 = pd.DataFrame(dc[dc["num"]==1].dtt2)

In [ ]:
jdpd_j = jdpd.JDP番号
jdpd_l = jdpd.地区名
jdpd_s = jdpd.区間番号修正
jdpd_km = jdpd.JDP担当範囲
jdpd_1 = jdpd.渋滞検知器番号1
jdpd_2 = jdpd.渋滞検知器番号2
jdpd_3 = jdpd.渋滞検知器番号3
jdpd_4 = jdpd.渋滞検知器番号4

df2 = []
dtt2["loca"] = 0
dtt2["jdp"] = 0
dtt2["secn"] = 0

for idx in range(jdpd.shape[0]):
#for idx in range(5):
    jdn = jdpd_j.values[idx]
    loca = jdpd_l.values[idx]
    secn = jdpd_s.values[idx]
    kmn = jdpd_km.values[idx]
    #jdn = jdp.JDP番号[idx]
    #secn = jdp.区間番号[idx]
    
    dtt2["jdp"] = jdn
    dtt2["loca"] = loca
    dtt2["secn"] = secn
    dtt2["kmn"] = kmn
    
    tempc=[]
    temp1 = dc[dc["num"]==jdpd_1.values[idx]]
    tempc = pd.merge(dtt2,temp1, on="dtt2")
    
    if pd.notna(jdpd_2.values[idx]):
        temp2 = dc[dc["num"]==jdpd_2.values[idx]]
        tempc = pd.merge(tempc,temp2, on="dtt2")
    
    if pd.notna(jdpd_3.values[idx]):
        temp3 = dc[dc["num"]==jdpd_3.values[idx]]
        tempc = pd.merge(tempc,temp3, on="dtt2")
    
    if pd.notna(jdpd_4.values[idx]):
        temp4 = dc[dc["num"]==jdpd_4.values[idx]]
        tempc = pd.merge(tempc,temp4, on="dtt2")
    
    tempv = tempc.values
    tempd = pd.DataFrame(tempv)
    df2.append(tempd)

In [ ]:
dfc2 = pd.concat(df2, axis = 0, ignore_index=True)

In [ ]:
dfc2[dfc2[2]==333]

In [ ]:
dfc2

In [ ]:
dfc2.insert(0,"idx",dfc2[0].astype(str)+"_"+dfc2[2].astype(str))

In [ ]:
dfc2

In [ ]:
dfinal = pd.merge(dfc2,dfcidx, on="idx", how="left")

In [ ]:
dfinal

In [ ]:
#ttt = dfinal[dfinal["0_x"]=="2021-04-30 11:10:00"]
#ttt2 = dfc2[dfc2[0]=="2021-04-30 11:10:00"]

In [ ]:
#ttt[ttt["1_x"]==35]
#ttt2[ttt2[1]==35]

In [ ]:
test=dfinal[pd.isna(dfinal["1_y"])].drop_duplicates(subset="1_x")

In [ ]:
test

In [ ]:
cong = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/cong04.csv", encoding="shift_jis")

In [ ]:
cong

In [ ]:
congd = cong.loc[:,["idx","cong"]]

In [ ]:
congd

In [ ]:
dfinal2 = pd.merge(dfinal,congd, on="idx", how="left")

In [ ]:
dfinal2

In [ ]:
dfinal2.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dfinal4.csv", index = False)

In [ ]:
dfinal2 = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dfinal4.csv", encoding="shift_jis")

In [ ]:
acc = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/accident.csv", encoding="shift_jis")

In [ ]:
accd = acc.loc[:,["idx","天候","事故の形態","交通状態","発生日_曜日","曜日種別E（営業）"]]

In [ ]:
accd["acci"]=1

In [ ]:
accd

In [ ]:
dfinal3 = pd.merge(dfinal2,accd, on="idx", how="left")

In [ ]:
dfinal3

In [ ]:
dfinal3.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dfinal4_2.csv", index = False)

In [ ]:
#dfinal3 = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dfinal4_2.csv", encoding="shift_jis")
dfinal3 = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dfinal4_2.csv")

In [ ]:
dfinal3["tm"]=pd.to_datetime(dfinal3["0_x"])

In [ ]:
dfinal3["week"]=dfinal3.tm.dt.weekday

In [ ]:
dfinal3["wcode"]=1

In [ ]:
#dc2.loc[(dfinal3.week>4)|(dc2.JDP状態=="A")|(dc2.JDP状態=="D"),"cong"]=2
dfinal3.loc[(dfinal3.week==5),"wcode"]=2
dfinal3.loc[(dfinal3.week==6),"wcode"]=3

In [ ]:
dfinal3["hour"]=dfinal3.tm.dt.hour

In [ ]:
dfinal3["hcode"]=2

In [ ]:
dfinal3.loc[(dfinal3.hour>6)&(dfinal3.hour<20),"hcode"]=1

In [ ]:
dfinal3["dy"]=pd.to_datetime(dfinal3[5])

In [ ]:
dfinal3.dy

In [ ]:
kyu = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/kyujitsu_2021.csv", header=None)

In [ ]:
kyu["dy"]=pd.to_datetime(kyu[0])

In [ ]:
kyu["kcode"]=1

In [ ]:
kyu.dy

In [ ]:
dfinal4 = pd.merge(dfinal3,kyu, on="dy", how="left")

In [ ]:
dfinal4

In [ ]:
dfinal4[~pd.isna(dfinal4.kcode)].kcode

In [ ]:
dfinal4.loc[(dfinal4.kcode==1),"wcode"]=3

In [ ]:
dfinal4.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dfinal4_3.csv", index = False)

In [ ]:
dfinal4 = pd.read_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dfinal4_3.csv")

In [ ]:
dfinal4

In [ ]:
dfinal4.columns

In [ ]:
dff = dfinal4.loc[:,["idx","1_x","2","4","5","3","7","11","trf","cong","acci","wcode","hcode","kcode"]]

In [ ]:
dff

In [ ]:
dff.to_csv("D:/ahn_pc/workfile/2021/阪神事故リスク/dff4.csv", index = False)